name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main 
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install lint tools
        run: |
          npm install -g htmlhint stylelint eslint
          
      - name: Lint HTML files
        run: |
          htmlhint luther-1.0.0/**/*.html

   
      - name: Lint CSS files
        run: |
          stylelint "luther-1.0.0/**/*.css"

      - name: Lint JS files
        run: |
          eslint "luther-1.0.0/**/*.js" || echo "No JS files or errors found"

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # For GitHub Actions to work
          action: "upload"
          app_location: "luther-1.0.0"
          output_location: "luther-1.0.0"
  
